name: 'daily_os'
version: '1.0.0'
config-version: 2

profile: 'daily_os'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  daily_os:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
